// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../../../main.h"
#include "../../../plugins/BLEScalePlugin.h"
#include "ui.h"
#include <Arduino.h>

// Flag to track if volumetric hold was triggered
static bool volumetricHoldTriggered = false;

void onBrewCancel(lv_event_t *e) {
    controller.deactivate();
    controller.clear();
}

void onBrewStart(lv_event_t *e) {
    if (controller.getUI()->handleBrewStartRequest()) {
        controller.activate();
    }
}

void onBrewTempLower(lv_event_t *e) { controller.lowerTemp(); }

void onBrewTempRaise(lv_event_t *e) { controller.raiseTemp(); }

void onBrewTimeLower(lv_event_t *e) { controller.lowerBrewTarget(); }

void onBrewTimeRaise(lv_event_t *e) { controller.raiseBrewTarget(); }

void onSteamTempLower(lv_event_t *e) { controller.lowerTemp(); }

void onSteamTempRaise(lv_event_t *e) { controller.raiseTemp(); }

void onSimpleProcessTargetTempOpen(lv_event_t *e) {
    if (controller.getMode() == MODE_WATER) {
        controller.getUI()->openTargetTemp(TargetTempKind::Water);
    } else {
        controller.getUI()->openTargetTemp(TargetTempKind::Steam);
    }
}

void onTargetTempLower(lv_event_t *e) { controller.lowerTemp(); }

void onTargetTempRaise(lv_event_t *e) { controller.raiseTemp(); }

void onTargetTempSaveBack(lv_event_t *e) { controller.getUI()->closeTargetTemp(); }

void onStatusScreenPause(lv_event_t *e) {
    if (controller.getUI()->isSteamPromptActive()) {
        controller.getUI()->onSteamPromptAction();
        return;
    }
    onBrewCancel(e);
}

void onBrewScreen(lv_event_t *e) {
    controller.getUI()->changeScreen(&ui_BrewScreen, &ui_BrewScreen_screen_init);
    controller.deactivate();
    controller.setMode(MODE_BREW);
}

void onWaterScreen(lv_event_t *e) {
    controller.getUI()->changeScreen(&ui_SimpleProcessScreen, &ui_SimpleProcessScreen_screen_init);
    controller.setMode(MODE_WATER);
    controller.deactivate();
}

void onSteamScreen(lv_event_t *e) {
    controller.getUI()->changeScreen(&ui_SimpleProcessScreen, &ui_SimpleProcessScreen_screen_init);
    controller.setMode(MODE_STEAM);
    controller.deactivate();
}

void onWakeup(lv_event_t *e) {
    const String landing = controller.getSettings().getStandbyLandingScreen();
    if (landing == "menu") {
        controller.deactivate();
        controller.setMode(MODE_BREW);
        controller.getUI()->changeScreen(&ui_MenuScreen, &ui_MenuScreen_screen_init);
    } else if (landing == "grind") {
        if (controller.getSettings().isDoseMeasureEnabled()) {
            controller.getUI()->changeScreen(&ui_GrindScreen, &ui_GrindScreen_singleDose_screen_init);
        } else {
            controller.getUI()->changeScreen(&ui_GrindScreen, &ui_GrindScreen_screen_init);
        }
        controller.deactivate();
        controller.setMode(MODE_GRIND);
    } else if (landing == "steam") {
        controller.getUI()->changeScreen(&ui_SimpleProcessScreen, &ui_SimpleProcessScreen_screen_init);
        controller.deactivate();
        controller.setMode(MODE_STEAM);
    } else if (landing == "water") {
        controller.getUI()->changeScreen(&ui_SimpleProcessScreen, &ui_SimpleProcessScreen_screen_init);
        controller.deactivate();
        controller.setMode(MODE_WATER);
    } else {
        controller.getUI()->changeScreen(&ui_BrewScreen, &ui_BrewScreen_screen_init);
        controller.deactivate();
        controller.setMode(MODE_BREW);
    }
}

void onScreensaverWake(lv_event_t *e) { controller.getUI()->onScreensaverWake(); }

void onLoadStarted(lv_event_t *e) { controller.onScreenReady(); }

void onStandby(lv_event_t *e) { controller.activateStandby(); }

void onGrindToggle(lv_event_t *e) {
  if (controller.getSettings().isDoseMeasureEnabled()) {
    controller.getUI()->onDoseMeasurePrimaryAction();
    return;
  }
  controller.isGrindActive() ? controller.deactivateGrind() : controller.activateGrind();
}

void onGrindTimeLower(lv_event_t *e) {
  if (controller.getSettings().isDoseMeasureEnabled()) {
    controller.getUI()->adjustDoseMeasureTarget(-0.5f);
    return;
  }
  controller.lowerGrindTarget();
}

void onGrindTimeRaise(lv_event_t *e) {
  if (controller.getSettings().isDoseMeasureEnabled()) {
    controller.getUI()->adjustDoseMeasureTarget(0.5f);
    return;
  }
  controller.raiseGrindTarget();
}

void onGrindDoseCountRaise(lv_event_t *e) {
  if (controller.getSettings().isDoseMeasureEnabled()) {
    controller.getUI()->adjustDoseMeasureDoseCount(1);
  }
}

void onGrindDoseCountLower(lv_event_t *e) {
  if (controller.getSettings().isDoseMeasureEnabled()) {
    controller.getUI()->adjustDoseMeasureDoseCount(-1);
  }
}

void onGrindReset(lv_event_t *e) {
  if (controller.getSettings().isDoseMeasureEnabled()) {
    controller.getUI()->resetDoseMeasureFlow();
  }
}

void onGrindEndBean(lv_event_t *e) {
  if (controller.getSettings().isDoseMeasureEnabled()) {
    controller.getUI()->onDoseMeasureEndBeanAction();
  }
}

void onGrindEndBrew(lv_event_t *e) {
  if (controller.getSettings().isDoseMeasureEnabled()) {
    controller.getUI()->onDoseMeasureEndBrewAction();
  }
}

void onProfilesClick(lv_event_t *e) { controller.getUI()->onProfileSwitch(); }

void onConfirmClick(lv_event_t *e) {
    (void)e;
}

void onSaveClick(lv_event_t *e) {
    (void)e;
}

void onMenuClick(lv_event_t *e) {
    controller.deactivate();
    controller.setMode(MODE_BREW);
    controller.getUI()->changeScreen(&ui_MenuScreen, &ui_MenuScreen_screen_init);
}

void onGrindScreen(lv_event_t *e) {
    if (controller.getSettings().isDoseMeasureEnabled()) {
        controller.getUI()->changeScreen(&ui_GrindScreen, &ui_GrindScreen_singleDose_screen_init);
    } else {
        controller.getUI()->changeScreen(&ui_GrindScreen, &ui_GrindScreen_screen_init);
    }
    controller.setMode(MODE_GRIND);
}

void onVolumetricClick(lv_event_t *e) {
    // Only execute click if hold wasn't triggered
    if (!volumetricHoldTriggered) {
        controller.onTargetToggle();
        controller.getUI()->markDirty();
    }
    // Reset the hold flag for next interaction
    volumetricHoldTriggered = false;
}

void onPreviousProfile(lv_event_t *e) { controller.getUI()->onPreviousProfile(); }

void onNextProfile(lv_event_t *e) { controller.getUI()->onNextProfile(); }

void onProfileLoad(lv_event_t *e) { controller.getUI()->onProfileSelect(); }

void onProfileSelect(lv_event_t *e) { controller.getUI()->onProfileSwitch(); }

void onFlush(lv_event_t *e) { controller.onFlush(); }

void onSimpleProcessToggle(lv_event_t *e) {
    if (controller.getMode() != MODE_STEAM) {
        controller.isActive() ? controller.deactivate() : controller.activate();
    }
}

void onProfileScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_ProfileScreen_previousProfileBtn, 30);
    lv_obj_set_ext_click_area(ui_ProfileScreen_nextProfileBtn, 30);
    lv_obj_set_ext_click_area(ui_ProfileScreen_chooseButton, 30);
    lv_obj_set_ext_click_area(ui_ProfileScreen_ImgButton1, 20);
}

void onMenuScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_MenuScreen_btnBrew, 15);
    lv_obj_set_ext_click_area(ui_MenuScreen_btnSteam, 15);
    lv_obj_set_ext_click_area(ui_MenuScreen_waterBtn, 15);
    lv_obj_set_ext_click_area(ui_MenuScreen_grindBtn, 15);
    lv_obj_set_ext_click_area(ui_MenuScreen_standbyButton, 20);
}

void onBrewScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_BrewScreen_profileName, 25);
    lv_obj_set_ext_click_area(ui_BrewScreen_menuLabel, 20);
    lv_obj_set_ext_click_area(ui_BrewScreen_profilesLabel, 20);
    lv_obj_set_ext_click_area(ui_BrewScreen_settingsButton, 20);
}

void onSimpleProcessScreenLoad(lv_event_t *e) {
    if (ui_SimpleProcessScreen_minusLabel) {
        lv_obj_set_ext_click_area(ui_SimpleProcessScreen_minusLabel, 20);
    }
    if (ui_SimpleProcessScreen_plusLabel) {
        lv_obj_set_ext_click_area(ui_SimpleProcessScreen_plusLabel, 20);
    }
    if (ui_SimpleProcessScreen_actionLabel) {
        lv_obj_set_ext_click_area(ui_SimpleProcessScreen_actionLabel, 25);
    }
    if (ui_SimpleProcessScreen_ImgButton6) {
        lv_obj_set_ext_click_area(ui_SimpleProcessScreen_ImgButton6, 20);
    }
    if (ui_SimpleProcessScreen_targetTemp) {
        lv_obj_set_ext_click_area(ui_SimpleProcessScreen_targetTemp, 20);
    }
}

void onTargetTempScreenLoad(lv_event_t *e) {
    if (ui_TargetTempScreen_minusLabel) {
        lv_obj_set_ext_click_area(ui_TargetTempScreen_minusLabel, 20);
    }
    if (ui_TargetTempScreen_plusLabel) {
        lv_obj_set_ext_click_area(ui_TargetTempScreen_plusLabel, 20);
    }
    if (ui_TargetTempScreen_saveLabel) {
        lv_obj_set_ext_click_area(ui_TargetTempScreen_saveLabel, 25);
    }
}

void onStatusScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_StatusScreen_pauseButton, 25);
    lv_obj_set_ext_click_area(ui_StatusScreen_ImgButton8, 20);
}

void onGrindScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_GrindScreen_upDurationButton, 40);
    lv_obj_set_ext_click_area(ui_GrindScreen_downDurationButton, 40);
    lv_obj_set_ext_click_area(ui_GrindScreen_startButton, 25);
    if (ui_GrindScreen_refreshButton) {
        lv_obj_set_ext_click_area(ui_GrindScreen_refreshButton, 25);
    }
    if (ui_GrindScreen_doseCountUp) {
        lv_obj_set_ext_click_area(ui_GrindScreen_doseCountUp, 40);
    }
    if (ui_GrindScreen_doseCountDown) {
        lv_obj_set_ext_click_area(ui_GrindScreen_doseCountDown, 40);
    }
    lv_obj_set_ext_click_area(ui_GrindScreen_ImgButton2, 20);
}

void onProfileSettings(lv_event_t *e) { controller.getUI()->changeBrewScreenMode(BrewScreenState::Settings); }

void onProfileSave(lv_event_t *e) {
    controller.onProfileSave();
    controller.getUI()->changeBrewScreenMode(BrewScreenState::Brew);
}

void onProfileAccept(lv_event_t *e) { controller.getUI()->changeBrewScreenMode(BrewScreenState::Brew); }

void onProfileSaveAsNew(lv_event_t *e) {
    controller.onProfileSaveAsNew();
    controller.getUI()->changeBrewScreenMode(BrewScreenState::Brew);
}

void onVolumetricHold(lv_event_t *e) {
    // Set flag to prevent click from firing when button is released
    volumetricHoldTriggered = true;

    controller.getClientController()->tare();
    BLEScales.tare();
}
