// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../ui.h"

lv_obj_t *ui_ScreensaverScreen = NULL;
lv_obj_t *ui_ScreensaverScreen_circle = NULL;
lv_obj_t *ui_ScreensaverScreen_logo = NULL;
lv_obj_t *ui_ScreensaverScreen_touch = NULL;

// event funtions
void ui_event_ScreensaverScreen(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onScreensaverWake(e);
    }
}

// build funtions

void ui_ScreensaverScreen_screen_init(void) {
    ui_ScreensaverScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreensaverScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_add_event_cb(ui_ScreensaverScreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED,
                        ui_ScreensaverScreen_screen_destroy);
    lv_obj_set_style_bg_color(ui_ScreensaverScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreensaverScreen, 77, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreensaverScreen_circle = lv_obj_create(ui_ScreensaverScreen);
    lv_obj_remove_style_all(ui_ScreensaverScreen_circle);
    lv_obj_set_width(ui_ScreensaverScreen_circle, 380);
    lv_obj_set_height(ui_ScreensaverScreen_circle, 380);
    lv_obj_set_align(ui_ScreensaverScreen_circle, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ScreensaverScreen_circle, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_ScreensaverScreen_circle, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreensaverScreen_circle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreensaverScreen_circle, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreensaverScreen_logo = lv_img_create(ui_ScreensaverScreen);
    lv_img_set_src(ui_ScreensaverScreen_logo, &ui_img_logo_png);
    lv_obj_set_width(ui_ScreensaverScreen_logo, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_ScreensaverScreen_logo, LV_SIZE_CONTENT); /// 1
    lv_obj_set_y(ui_ScreensaverScreen_logo, 10);
    lv_obj_set_align(ui_ScreensaverScreen_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScreensaverScreen_logo, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_ScreensaverScreen_logo, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(ui_ScreensaverScreen_logo, 210);
    ui_object_set_themeable_style_property(ui_ScreensaverScreen_logo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_ScreensaverScreen_logo, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    ui_ScreensaverScreen_touch = lv_img_create(ui_ScreensaverScreen);
    lv_img_set_src(ui_ScreensaverScreen_touch, &ui_img_1732953241);
    lv_obj_set_width(ui_ScreensaverScreen_touch, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_ScreensaverScreen_touch, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_ScreensaverScreen_touch, 0);
    lv_obj_set_y(ui_ScreensaverScreen_touch, 150);
    lv_obj_set_align(ui_ScreensaverScreen_touch, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScreensaverScreen_touch, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_ScreensaverScreen_touch, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(ui_ScreensaverScreen_touch, 210);
    ui_object_set_themeable_style_property(ui_ScreensaverScreen_touch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_ScreensaverScreen_touch, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    lv_obj_add_event_cb(ui_ScreensaverScreen, ui_event_ScreensaverScreen, LV_EVENT_ALL, NULL);
}

void ui_ScreensaverScreen_screen_destroy(void) {
    if (ui_ScreensaverScreen)
        lv_obj_del(ui_ScreensaverScreen);

    // NULL screen variables
    ui_ScreensaverScreen = NULL;
    ui_ScreensaverScreen_circle = NULL;
    ui_ScreensaverScreen_logo = NULL;
    ui_ScreensaverScreen_touch = NULL;
}
