// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../ui.h"

lv_obj_t *uic_SimpleProcessScreen_dials_tempText;
lv_obj_t *uic_SimpleProcessScreen_dials_pressureText;
lv_obj_t *uic_SimpleProcessScreen_dials_pressureTarget;
lv_obj_t *uic_SimpleProcessScreen_dials_pressureGauge;
lv_obj_t *uic_SimpleProcessScreen_dials_tempTarget;
lv_obj_t *uic_SimpleProcessScreen_dials_tempGauge;
lv_obj_t *ui_SimpleProcessScreen = NULL;
lv_obj_t *ui_SimpleProcessScreen_dials = NULL;
lv_obj_t *ui_SimpleProcessScreen_layout = NULL;
lv_obj_t *ui_SimpleProcessScreen_ImgButton6 = NULL;
lv_obj_t *ui_SimpleProcessScreen_contentPanel5 = NULL;
lv_obj_t *ui_SimpleProcessScreen_mainLabel5 = NULL;
lv_obj_t *ui_SimpleProcessScreen_actionLabel = NULL;
lv_obj_t *ui_SimpleProcessScreen_minusLabel = NULL;
lv_obj_t *ui_SimpleProcessScreen_plusLabel = NULL;
lv_obj_t *ui_SimpleProcessScreen_targetTemp = NULL;
lv_obj_t *ui_SimpleProcessScreen_Image9 = NULL;
// event funtions
void ui_event_SimpleProcessScreen(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        onMenuClick(e);
    }
    if (event_code == LV_EVENT_SCREEN_LOADED) {
        onSimpleProcessScreenLoad(e);
    }
}

void ui_event_SimpleProcessScreen_ImgButton6(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onMenuClick(e);
    }
}

void ui_event_SimpleProcessScreen_minusLabel(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onSteamTempLower(e);
    }
}

void ui_event_SimpleProcessScreen_plusLabel(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onSteamTempRaise(e);
    }
}

static void ui_event_SimpleProcessScreen_targetTemp(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onSimpleProcessTargetTempOpen(e);
    }
}

// build funtions

void ui_SimpleProcessScreen_screen_init(void) {
    ui_SimpleProcessScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SimpleProcessScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_add_event_cb(ui_SimpleProcessScreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED,
                        ui_SimpleProcessScreen_screen_destroy);
    ui_object_set_themeable_style_property(ui_SimpleProcessScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_SimpleProcessScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Dark);

    lv_obj_t *ui_SimpleProcessScreen_background = lv_img_create(ui_SimpleProcessScreen);
    lv_img_set_src(ui_SimpleProcessScreen_background, &ui_img_background_minimal);
    lv_obj_set_align(ui_SimpleProcessScreen_background, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SimpleProcessScreen_background, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(ui_SimpleProcessScreen_background, LV_OBJ_FLAG_SCROLLABLE);

    ui_SimpleProcessScreen_dials = ui_dials_create(ui_SimpleProcessScreen);
    lv_obj_set_x(ui_SimpleProcessScreen_dials, 0);
    lv_obj_set_y(ui_SimpleProcessScreen_dials, 0);

    ui_SimpleProcessScreen_layout = ui_layout_main_create(ui_SimpleProcessScreen);
    lv_obj_t *layout_top = ui_comp_get_child(ui_SimpleProcessScreen_layout, UI_COMP_LAYOUT_MAIN_TOP);
    lv_obj_t *layout_main = ui_comp_get_child(ui_SimpleProcessScreen_layout, UI_COMP_LAYOUT_MAIN_MAIN);
    lv_obj_t *layout_main_left = ui_comp_get_child(ui_SimpleProcessScreen_layout, UI_COMP_LAYOUT_MAIN_MAIN_LEFT);
    lv_obj_t *layout_main_right = ui_comp_get_child(ui_SimpleProcessScreen_layout, UI_COMP_LAYOUT_MAIN_MAIN_RIGHT);
    lv_obj_t *layout_base_top = ui_comp_get_child(ui_SimpleProcessScreen_layout, UI_COMP_LAYOUT_MAIN_BASE_TOP);
    lv_obj_t *layout_base_bottom = ui_comp_get_child(ui_SimpleProcessScreen_layout, UI_COMP_LAYOUT_MAIN_BASE_BOTTOM);

    ui_button_menu_create(layout_top);

    ui_SimpleProcessScreen_mainLabel5 = lv_label_create(layout_main);
    lv_obj_set_width(ui_SimpleProcessScreen_mainLabel5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SimpleProcessScreen_mainLabel5, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SimpleProcessScreen_mainLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SimpleProcessScreen_mainLabel5, "Steam");
    lv_obj_set_style_text_color(ui_SimpleProcessScreen_mainLabel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SimpleProcessScreen_mainLabel5, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SimpleProcessScreen_mainLabel5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SimpleProcessScreen_mainLabel5, &ui_font_sfprodisplaybold_45,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SimpleProcessScreen_actionLabel = lv_label_create(layout_base_top);
    lv_obj_set_width(ui_SimpleProcessScreen_actionLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_SimpleProcessScreen_actionLabel, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_SimpleProcessScreen_actionLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SimpleProcessScreen_actionLabel, "start");
    lv_obj_set_style_text_align(ui_SimpleProcessScreen_actionLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SimpleProcessScreen_actionLabel, &ui_font_sfprodisplaybold_24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SimpleProcessScreen_actionLabel, lv_color_hex(0x727373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SimpleProcessScreen_actionLabel, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_SimpleProcessScreen_actionLabel, LV_OBJ_FLAG_CLICKABLE);

    ui_SimpleProcessScreen_minusLabel = lv_label_create(layout_main_left);
    lv_obj_set_width(ui_SimpleProcessScreen_minusLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_SimpleProcessScreen_minusLabel, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_SimpleProcessScreen_minusLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_SimpleProcessScreen_minusLabel, "-");
    lv_obj_set_style_text_align(ui_SimpleProcessScreen_minusLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SimpleProcessScreen_minusLabel, &ui_font_sfprodisplaybold_45,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SimpleProcessScreen_minusLabel, lv_color_hex(0x727374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SimpleProcessScreen_minusLabel, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_SimpleProcessScreen_minusLabel, LV_OBJ_FLAG_CLICKABLE);

    ui_SimpleProcessScreen_plusLabel = lv_label_create(layout_main_right);
    lv_obj_set_width(ui_SimpleProcessScreen_plusLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_SimpleProcessScreen_plusLabel, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_SimpleProcessScreen_plusLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SimpleProcessScreen_plusLabel, "+");
    lv_obj_set_style_text_align(ui_SimpleProcessScreen_plusLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SimpleProcessScreen_plusLabel, &ui_font_sfprodisplaybold_45,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SimpleProcessScreen_plusLabel, lv_color_hex(0x727374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SimpleProcessScreen_plusLabel, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_SimpleProcessScreen_plusLabel, LV_OBJ_FLAG_CLICKABLE);

    ui_SimpleProcessScreen_targetTemp = lv_label_create(layout_base_bottom);
    lv_obj_set_width(ui_SimpleProcessScreen_targetTemp, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_SimpleProcessScreen_targetTemp, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_SimpleProcessScreen_targetTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SimpleProcessScreen_targetTemp, "145°C");
    lv_obj_set_style_text_color(ui_SimpleProcessScreen_targetTemp, lv_color_hex(0x727373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SimpleProcessScreen_targetTemp, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SimpleProcessScreen_targetTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SimpleProcessScreen_targetTemp, &ui_font_sfprodisplaybold_18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_SimpleProcessScreen_targetTemp, LV_OBJ_FLAG_CLICKABLE);

    lv_obj_add_event_cb(ui_SimpleProcessScreen_minusLabel, ui_event_SimpleProcessScreen_minusLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SimpleProcessScreen_plusLabel, ui_event_SimpleProcessScreen_plusLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SimpleProcessScreen_targetTemp, ui_event_SimpleProcessScreen_targetTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SimpleProcessScreen, ui_event_SimpleProcessScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SimpleProcessScreen_actionLabel, onSimpleProcessToggle, LV_EVENT_CLICKED, NULL);
    uic_SimpleProcessScreen_dials_tempGauge = ui_comp_get_child(ui_SimpleProcessScreen_dials, UI_COMP_DIALS_TEMPGAUGE);
    uic_SimpleProcessScreen_dials_tempTarget = ui_comp_get_child(ui_SimpleProcessScreen_dials, UI_COMP_DIALS_TEMPTARGET);
    uic_SimpleProcessScreen_dials_pressureGauge = ui_comp_get_child(ui_SimpleProcessScreen_dials, UI_COMP_DIALS_PRESSUREGAUGE);
    uic_SimpleProcessScreen_dials_pressureTarget = ui_comp_get_child(ui_SimpleProcessScreen_dials, UI_COMP_DIALS_PRESSURETARGET);
    uic_SimpleProcessScreen_dials_pressureText = ui_comp_get_child(ui_SimpleProcessScreen_dials, UI_COMP_DIALS_PRESSURETEXT);
    uic_SimpleProcessScreen_dials_tempText = ui_comp_get_child(ui_SimpleProcessScreen_dials, UI_COMP_DIALS_TEMPTEXT);
}

void ui_SimpleProcessScreen_screen_destroy(void) {
    if (ui_SimpleProcessScreen)
        lv_obj_del(ui_SimpleProcessScreen);

    // NULL screen variables
    ui_SimpleProcessScreen = NULL;
    ui_SimpleProcessScreen_dials = NULL;
    ui_SimpleProcessScreen_layout = NULL;
    uic_SimpleProcessScreen_dials_tempGauge = NULL;
    uic_SimpleProcessScreen_dials_tempTarget = NULL;
    uic_SimpleProcessScreen_dials_pressureGauge = NULL;
    uic_SimpleProcessScreen_dials_pressureTarget = NULL;
    uic_SimpleProcessScreen_dials_pressureText = NULL;
    uic_SimpleProcessScreen_dials_tempText = NULL;
    ui_SimpleProcessScreen_ImgButton6 = NULL;
    ui_SimpleProcessScreen_contentPanel5 = NULL;
    ui_SimpleProcessScreen_mainLabel5 = NULL;
    ui_SimpleProcessScreen_actionLabel = NULL;
    ui_SimpleProcessScreen_minusLabel = NULL;
    ui_SimpleProcessScreen_plusLabel = NULL;
    ui_SimpleProcessScreen_targetTemp = NULL;
    ui_SimpleProcessScreen_Image9 = NULL;
}
