// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef UI_SCREENSAVERSCREEN_H
#define UI_SCREENSAVERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreensaverScreen
extern void ui_ScreensaverScreen_screen_init(void);
extern void ui_ScreensaverScreen_screen_destroy(void);
extern void ui_event_ScreensaverScreen(lv_event_t *e);
extern lv_obj_t *ui_ScreensaverScreen;
extern lv_obj_t *ui_ScreensaverScreen_circle;
extern lv_obj_t *ui_ScreensaverScreen_logo;
extern lv_obj_t *ui_ScreensaverScreen_touch;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
