// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef UI_SIMPLEPROCESSSCREEN_H
#define UI_SIMPLEPROCESSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SimpleProcessScreen
extern void ui_SimpleProcessScreen_screen_init(void);
extern void ui_SimpleProcessScreen_screen_destroy(void);
extern void ui_event_SimpleProcessScreen(lv_event_t *e);
extern lv_obj_t *ui_SimpleProcessScreen;
extern lv_obj_t *ui_SimpleProcessScreen_dials;
extern lv_obj_t *ui_SimpleProcessScreen_layout;
extern void ui_event_SimpleProcessScreen_ImgButton6(lv_event_t *e);
extern lv_obj_t *ui_SimpleProcessScreen_ImgButton6;
extern lv_obj_t *ui_SimpleProcessScreen_contentPanel5;
extern lv_obj_t *ui_SimpleProcessScreen_mainLabel5;
extern lv_obj_t *ui_SimpleProcessScreen_actionLabel;
extern void ui_event_SimpleProcessScreen_minusLabel(lv_event_t *e);
extern lv_obj_t *ui_SimpleProcessScreen_minusLabel;
extern void ui_event_SimpleProcessScreen_plusLabel(lv_event_t *e);
extern lv_obj_t *ui_SimpleProcessScreen_plusLabel;
extern lv_obj_t *ui_SimpleProcessScreen_targetTemp;
extern lv_obj_t *ui_SimpleProcessScreen_Image9;
// CUSTOM VARIABLES
extern lv_obj_t *uic_SimpleProcessScreen_dials_tempGauge;
extern lv_obj_t *uic_SimpleProcessScreen_dials_tempTarget;
extern lv_obj_t *uic_SimpleProcessScreen_dials_pressureGauge;
extern lv_obj_t *uic_SimpleProcessScreen_dials_pressureTarget;
extern lv_obj_t *uic_SimpleProcessScreen_dials_pressureText;
extern lv_obj_t *uic_SimpleProcessScreen_dials_tempText;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
