// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../ui.h"

lv_obj_t *ui_TargetTempScreen = NULL;
lv_obj_t *ui_TargetTempScreen_layout = NULL;
lv_obj_t *ui_TargetTempScreen_titleLabel = NULL;
lv_obj_t *ui_TargetTempScreen_valueLabel = NULL;
lv_obj_t *ui_TargetTempScreen_minusLabel = NULL;
lv_obj_t *ui_TargetTempScreen_plusLabel = NULL;
lv_obj_t *ui_TargetTempScreen_saveLabel = NULL;

// event functions
void ui_event_TargetTempScreen(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        onTargetTempSaveBack(e);
    }
    if (event_code == LV_EVENT_SCREEN_LOADED) {
        onTargetTempScreenLoad(e);
    }
}

static void ui_event_TargetTempScreen_saveLabel(lv_event_t *e) {
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        onTargetTempSaveBack(e);
    }
}

static void ui_event_TargetTempScreen_minusLabel(lv_event_t *e) {
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        onTargetTempLower(e);
    }
}

static void ui_event_TargetTempScreen_plusLabel(lv_event_t *e) {
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        onTargetTempRaise(e);
    }
}

// build functions
void ui_TargetTempScreen_screen_init(void) {
    ui_TargetTempScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TargetTempScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_add_event_cb(ui_TargetTempScreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED,
                        ui_TargetTempScreen_screen_destroy);
    ui_object_set_themeable_style_property(ui_TargetTempScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_TargetTempScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Dark);

    lv_obj_t *ui_TargetTempScreen_background = lv_img_create(ui_TargetTempScreen);
    lv_img_set_src(ui_TargetTempScreen_background, &ui_img_background_minimal);
    lv_obj_set_align(ui_TargetTempScreen_background, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TargetTempScreen_background, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(ui_TargetTempScreen_background, LV_OBJ_FLAG_SCROLLABLE);

    ui_TargetTempScreen_layout = ui_layout_settings_single_create(ui_TargetTempScreen);
    lv_obj_t *layout_title = ui_comp_get_child(ui_TargetTempScreen_layout, UI_COMP_LAYOUT_SETTINGS_SINGLE_TITLE);
    lv_obj_t *layout_left = ui_comp_get_child(ui_TargetTempScreen_layout, UI_COMP_LAYOUT_SETTINGS_SINGLE_LEFT);
    lv_obj_t *layout_right = ui_comp_get_child(ui_TargetTempScreen_layout, UI_COMP_LAYOUT_SETTINGS_SINGLE_RIGHT);
    lv_obj_t *layout_main = ui_comp_get_child(ui_TargetTempScreen_layout, UI_COMP_LAYOUT_SETTINGS_SINGLE_MAIN);
    lv_obj_t *layout_base_top = ui_comp_get_child(ui_TargetTempScreen_layout, UI_COMP_LAYOUT_SETTINGS_SINGLE_BASE_TOP);

    ui_TargetTempScreen_titleLabel = lv_label_create(layout_title);
    lv_obj_set_width(ui_TargetTempScreen_titleLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_TargetTempScreen_titleLabel, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_TargetTempScreen_titleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TargetTempScreen_titleLabel, "steam temperature");
    lv_obj_set_style_text_align(ui_TargetTempScreen_titleLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TargetTempScreen_titleLabel, &ui_font_sfprodisplaybold_24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_TargetTempScreen_titleLabel, lv_color_hex(0x727373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TargetTempScreen_titleLabel, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TargetTempScreen_valueLabel = lv_label_create(layout_main);
    lv_obj_set_width(ui_TargetTempScreen_valueLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_TargetTempScreen_valueLabel, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_TargetTempScreen_valueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TargetTempScreen_valueLabel, "145°C");
    lv_obj_set_style_text_align(ui_TargetTempScreen_valueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TargetTempScreen_valueLabel, &ui_font_sfprodisplaybold_45,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_TargetTempScreen_valueLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TargetTempScreen_valueLabel, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TargetTempScreen_minusLabel = lv_label_create(layout_left);
    lv_obj_set_width(ui_TargetTempScreen_minusLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_TargetTempScreen_minusLabel, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_TargetTempScreen_minusLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TargetTempScreen_minusLabel, "-");
    lv_obj_set_style_text_align(ui_TargetTempScreen_minusLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TargetTempScreen_minusLabel, &ui_font_sfprodisplaybold_45,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_TargetTempScreen_minusLabel, lv_color_hex(0x727373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TargetTempScreen_minusLabel, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_TargetTempScreen_minusLabel, LV_OBJ_FLAG_CLICKABLE);

    ui_TargetTempScreen_plusLabel = lv_label_create(layout_right);
    lv_obj_set_width(ui_TargetTempScreen_plusLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_TargetTempScreen_plusLabel, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_TargetTempScreen_plusLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TargetTempScreen_plusLabel, "+");
    lv_obj_set_style_text_align(ui_TargetTempScreen_plusLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TargetTempScreen_plusLabel, &ui_font_sfprodisplaybold_45,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_TargetTempScreen_plusLabel, lv_color_hex(0x727373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TargetTempScreen_plusLabel, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_TargetTempScreen_plusLabel, LV_OBJ_FLAG_CLICKABLE);

    ui_TargetTempScreen_saveLabel = lv_label_create(layout_base_top);
    lv_obj_set_width(ui_TargetTempScreen_saveLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_TargetTempScreen_saveLabel, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_TargetTempScreen_saveLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TargetTempScreen_saveLabel, "save");
    lv_obj_set_style_text_align(ui_TargetTempScreen_saveLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TargetTempScreen_saveLabel, &ui_font_sfprodisplaybold_24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_TargetTempScreen_saveLabel, lv_color_hex(0x727373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TargetTempScreen_saveLabel, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_TargetTempScreen_saveLabel, LV_OBJ_FLAG_CLICKABLE);

    lv_obj_add_event_cb(ui_TargetTempScreen_saveLabel, ui_event_TargetTempScreen_saveLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TargetTempScreen_minusLabel, ui_event_TargetTempScreen_minusLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TargetTempScreen_plusLabel, ui_event_TargetTempScreen_plusLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TargetTempScreen, ui_event_TargetTempScreen, LV_EVENT_ALL, NULL);
}

void ui_TargetTempScreen_screen_destroy(void) {
    if (ui_TargetTempScreen)
        lv_obj_del(ui_TargetTempScreen);

    ui_TargetTempScreen = NULL;
    ui_TargetTempScreen_layout = NULL;
    ui_TargetTempScreen_titleLabel = NULL;
    ui_TargetTempScreen_valueLabel = NULL;
    ui_TargetTempScreen_minusLabel = NULL;
    ui_TargetTempScreen_plusLabel = NULL;
    ui_TargetTempScreen_saveLabel = NULL;
}
