// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef _UI_TARGETTEMPSCREEN_H
#define _UI_TARGETTEMPSCREEN_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TargetTempScreen
extern void ui_TargetTempScreen_screen_init(void);
extern void ui_TargetTempScreen_screen_destroy(void);
extern void ui_event_TargetTempScreen(lv_event_t *e);
extern lv_obj_t *ui_TargetTempScreen;
extern lv_obj_t *ui_TargetTempScreen_layout;
extern lv_obj_t *ui_TargetTempScreen_titleLabel;
extern lv_obj_t *ui_TargetTempScreen_valueLabel;
extern lv_obj_t *ui_TargetTempScreen_minusLabel;
extern lv_obj_t *ui_TargetTempScreen_plusLabel;
extern lv_obj_t *ui_TargetTempScreen_saveLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
