// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../ui.h"

// COMPONENT layout_settings

static void apply_container_style(lv_obj_t *obj) {
    lv_obj_remove_style_all(obj);
    lv_obj_set_style_bg_opa(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_flex_flow(obj, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(obj, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
}

lv_obj_t *ui_layout_settings_create(lv_obj_t *comp_parent) {
    lv_obj_t *cui_layout;
    cui_layout = lv_obj_create(comp_parent);
    apply_container_style(cui_layout);
    lv_obj_set_width(cui_layout, 480);
    lv_obj_set_height(cui_layout, 480);
    lv_obj_set_align(cui_layout, LV_ALIGN_TOP_LEFT);
    lv_obj_set_pos(cui_layout, 0, 0);

    lv_obj_t *cui_top = lv_obj_create(cui_layout);
    apply_container_style(cui_top);
    lv_obj_set_size(cui_top, 100, 26);
    lv_obj_set_pos(cui_top, 190, 58);
    lv_obj_set_align(cui_top, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_top_title = lv_obj_create(cui_layout);
    apply_container_style(cui_top_title);
    lv_obj_set_size(cui_top_title, 200, 26);
    lv_obj_set_pos(cui_top_title, 140, 157);
    lv_obj_set_align(cui_top_title, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_top_left = lv_obj_create(cui_layout);
    apply_container_style(cui_top_left);
    lv_obj_set_size(cui_top_left, 50, 50);
    lv_obj_set_pos(cui_top_left, 90, 183);
    lv_obj_set_align(cui_top_left, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_top_right = lv_obj_create(cui_layout);
    apply_container_style(cui_top_right);
    lv_obj_set_size(cui_top_right, 50, 50);
    lv_obj_set_pos(cui_top_right, 340, 183);
    lv_obj_set_align(cui_top_right, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_main_top = lv_obj_create(cui_layout);
    apply_container_style(cui_main_top);
    lv_obj_set_size(cui_main_top, 200, 50);
    lv_obj_set_pos(cui_main_top, 140, 183);
    lv_obj_set_align(cui_main_top, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_bottom_title = lv_obj_create(cui_layout);
    apply_container_style(cui_bottom_title);
    lv_obj_set_size(cui_bottom_title, 200, 26);
    lv_obj_set_pos(cui_bottom_title, 140, 248);
    lv_obj_set_align(cui_bottom_title, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_bottom_left = lv_obj_create(cui_layout);
    apply_container_style(cui_bottom_left);
    lv_obj_set_size(cui_bottom_left, 50, 50);
    lv_obj_set_pos(cui_bottom_left, 90, 274);
    lv_obj_set_align(cui_bottom_left, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_bottom_right = lv_obj_create(cui_layout);
    apply_container_style(cui_bottom_right);
    lv_obj_set_size(cui_bottom_right, 50, 50);
    lv_obj_set_pos(cui_bottom_right, 340, 274);
    lv_obj_set_align(cui_bottom_right, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_main_bottom = lv_obj_create(cui_layout);
    apply_container_style(cui_main_bottom);
    lv_obj_set_size(cui_main_bottom, 200, 50);
    lv_obj_set_pos(cui_main_bottom, 140, 274);
    lv_obj_set_align(cui_main_bottom, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_base_top = lv_obj_create(cui_layout);
    apply_container_style(cui_base_top);
    lv_obj_set_size(cui_base_top, 100, 26);
    lv_obj_set_pos(cui_base_top, 190, 370);
    lv_obj_set_align(cui_base_top, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_ring_bottom_main = lv_obj_create(cui_layout);
    apply_container_style(cui_ring_bottom_main);
    lv_obj_set_size(cui_ring_bottom_main, 100, 26);
    lv_obj_set_pos(cui_ring_bottom_main, 190, 430);
    lv_obj_set_align(cui_ring_bottom_main, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_ring_bottom_left = lv_obj_create(cui_layout);
    apply_container_style(cui_ring_bottom_left);
    lv_obj_set_size(cui_ring_bottom_left, 45, 26);
    lv_obj_set_pos(cui_ring_bottom_left, 190, 430);
    lv_obj_set_align(cui_ring_bottom_left, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_ring_bottom_right = lv_obj_create(cui_layout);
    apply_container_style(cui_ring_bottom_right);
    lv_obj_set_size(cui_ring_bottom_right, 45, 26);
    lv_obj_set_pos(cui_ring_bottom_right, 245, 430);
    lv_obj_set_align(cui_ring_bottom_right, LV_ALIGN_TOP_LEFT);

    lv_obj_t **children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LAYOUT_SETTINGS_NUM);
    children[UI_COMP_LAYOUT_SETTINGS_ROOT] = cui_layout;
    children[UI_COMP_LAYOUT_SETTINGS_TOP] = cui_top;
    children[UI_COMP_LAYOUT_SETTINGS_TOP_TITLE] = cui_top_title;
    children[UI_COMP_LAYOUT_SETTINGS_TOP_LEFT] = cui_top_left;
    children[UI_COMP_LAYOUT_SETTINGS_TOP_RIGHT] = cui_top_right;
    children[UI_COMP_LAYOUT_SETTINGS_MAIN_TOP] = cui_main_top;
    children[UI_COMP_LAYOUT_SETTINGS_BOTTOM_TITLE] = cui_bottom_title;
    children[UI_COMP_LAYOUT_SETTINGS_BOTTOM_LEFT] = cui_bottom_left;
    children[UI_COMP_LAYOUT_SETTINGS_BOTTOM_RIGHT] = cui_bottom_right;
    children[UI_COMP_LAYOUT_SETTINGS_MAIN_BOTTOM] = cui_main_bottom;
    children[UI_COMP_LAYOUT_SETTINGS_BASE_TOP] = cui_base_top;
    children[UI_COMP_LAYOUT_SETTINGS_RING_BOTTOM_MAIN] = cui_ring_bottom_main;
    children[UI_COMP_LAYOUT_SETTINGS_RING_BOTTOM_LEFT] = cui_ring_bottom_left;
    children[UI_COMP_LAYOUT_SETTINGS_RING_BOTTOM_RIGHT] = cui_ring_bottom_right;
    lv_obj_add_event_cb(cui_layout, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_layout, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_layout_settings_create_hook(cui_layout);
    return cui_layout;
}
