// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef _UI_COMP_LAYOUT_SETTINGS_H
#define _UI_COMP_LAYOUT_SETTINGS_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT layout_settings
#define UI_COMP_LAYOUT_SETTINGS_ROOT 0
#define UI_COMP_LAYOUT_SETTINGS_TOP 1
#define UI_COMP_LAYOUT_SETTINGS_TOP_TITLE 2
#define UI_COMP_LAYOUT_SETTINGS_TOP_LEFT 3
#define UI_COMP_LAYOUT_SETTINGS_TOP_RIGHT 4
#define UI_COMP_LAYOUT_SETTINGS_MAIN_TOP 5
#define UI_COMP_LAYOUT_SETTINGS_BOTTOM_TITLE 6
#define UI_COMP_LAYOUT_SETTINGS_BOTTOM_LEFT 7
#define UI_COMP_LAYOUT_SETTINGS_BOTTOM_RIGHT 8
#define UI_COMP_LAYOUT_SETTINGS_MAIN_BOTTOM 9
#define UI_COMP_LAYOUT_SETTINGS_BASE_TOP 10
#define UI_COMP_LAYOUT_SETTINGS_RING_BOTTOM_MAIN 11
#define UI_COMP_LAYOUT_SETTINGS_RING_BOTTOM_LEFT 12
#define UI_COMP_LAYOUT_SETTINGS_RING_BOTTOM_RIGHT 13
#define _UI_COMP_LAYOUT_SETTINGS_NUM 14
lv_obj_t *ui_layout_settings_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
