// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef _UI_COMP_BUTTON_MENU_H
#define _UI_COMP_BUTTON_MENU_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT button_menu
lv_obj_t *ui_button_menu_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
