// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef _UI_COMP_LAYOUT_MAIN_H
#define _UI_COMP_LAYOUT_MAIN_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT layout_main
#define UI_COMP_LAYOUT_MAIN_ROOT 0
#define UI_COMP_LAYOUT_MAIN_TOP 1
#define UI_COMP_LAYOUT_MAIN_MID_TOP_RIGHT 2
#define UI_COMP_LAYOUT_MAIN_MID_TOP_LEFT 3
#define UI_COMP_LAYOUT_MAIN_MID_RIGHT 4
#define UI_COMP_LAYOUT_MAIN_MID_LEFT 5
#define UI_COMP_LAYOUT_MAIN_MAIN_LEFT 6
#define UI_COMP_LAYOUT_MAIN_MAIN_RIGHT 7
#define UI_COMP_LAYOUT_MAIN_MAIN 8
#define UI_COMP_LAYOUT_MAIN_MAIN_SUB 9
#define UI_COMP_LAYOUT_MAIN_BASE_TOP 10
#define UI_COMP_LAYOUT_MAIN_BASE_BOTTOM 11
#define UI_COMP_LAYOUT_MAIN_RING_BOTTOM_MAIN 12
#define UI_COMP_LAYOUT_MAIN_RING_BOTTOM_LEFT 13
#define UI_COMP_LAYOUT_MAIN_RING_BOTTOM_RIGHT 14
#define _UI_COMP_LAYOUT_MAIN_NUM 15
lv_obj_t *ui_layout_main_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
