// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../ui.h"

// COMPONENT button_confirm

lv_obj_t *ui_button_confirm_create(lv_obj_t *comp_parent) {
    lv_obj_t *cui_confirm;
    cui_confirm = lv_label_create(comp_parent);
    lv_obj_set_width(cui_confirm, LV_SIZE_CONTENT);
    lv_obj_set_height(cui_confirm, LV_SIZE_CONTENT);
    lv_obj_set_align(cui_confirm, LV_ALIGN_CENTER);
    lv_label_set_text(cui_confirm, "confirm");
    lv_obj_set_style_text_align(cui_confirm, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_confirm, &ui_font_sfprodisplaybold_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(cui_confirm, lv_color_hex(0x727373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_confirm, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(cui_confirm, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(cui_confirm, onConfirmClick, LV_EVENT_CLICKED, NULL);
    return cui_confirm;
}
