// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../ui.h"

// COMPONENT layout_settings_single

static void apply_container_style(lv_obj_t *obj) {
    lv_obj_remove_style_all(obj);
    lv_obj_set_style_bg_opa(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_flex_flow(obj, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(obj, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
}

lv_obj_t *ui_layout_settings_single_create(lv_obj_t *comp_parent) {
    lv_obj_t *cui_layout;
    cui_layout = lv_obj_create(comp_parent);
    apply_container_style(cui_layout);
    lv_obj_set_width(cui_layout, 480);
    lv_obj_set_height(cui_layout, 480);
    lv_obj_set_align(cui_layout, LV_ALIGN_TOP_LEFT);
    lv_obj_set_pos(cui_layout, 0, 0);

    lv_obj_t *cui_title = lv_obj_create(cui_layout);
    apply_container_style(cui_title);
    lv_obj_set_size(cui_title, 200, 26);
    lv_obj_set_pos(cui_title, 140, 189);
    lv_obj_set_align(cui_title, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_left = lv_obj_create(cui_layout);
    apply_container_style(cui_left);
    lv_obj_set_size(cui_left, 50, 50);
    lv_obj_set_pos(cui_left, 90, 215);
    lv_obj_set_align(cui_left, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_right = lv_obj_create(cui_layout);
    apply_container_style(cui_right);
    lv_obj_set_size(cui_right, 50, 50);
    lv_obj_set_pos(cui_right, 340, 215);
    lv_obj_set_align(cui_right, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_main = lv_obj_create(cui_layout);
    apply_container_style(cui_main);
    lv_obj_set_size(cui_main, 200, 50);
    lv_obj_set_pos(cui_main, 140, 215);
    lv_obj_set_align(cui_main, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_base_top = lv_obj_create(cui_layout);
    apply_container_style(cui_base_top);
    lv_obj_set_size(cui_base_top, 100, 26);
    lv_obj_set_pos(cui_base_top, 190, 370);
    lv_obj_set_align(cui_base_top, LV_ALIGN_TOP_LEFT);

    lv_obj_t **children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LAYOUT_SETTINGS_SINGLE_NUM);
    children[UI_COMP_LAYOUT_SETTINGS_SINGLE_ROOT] = cui_layout;
    children[UI_COMP_LAYOUT_SETTINGS_SINGLE_TITLE] = cui_title;
    children[UI_COMP_LAYOUT_SETTINGS_SINGLE_LEFT] = cui_left;
    children[UI_COMP_LAYOUT_SETTINGS_SINGLE_RIGHT] = cui_right;
    children[UI_COMP_LAYOUT_SETTINGS_SINGLE_MAIN] = cui_main;
    children[UI_COMP_LAYOUT_SETTINGS_SINGLE_BASE_TOP] = cui_base_top;
    lv_obj_add_event_cb(cui_layout, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_layout, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_layout_settings_single_create_hook(cui_layout);
    return cui_layout;
}
