// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../ui.h"

// COMPONENT layout_main

static void apply_container_style(lv_obj_t *obj) {
    lv_obj_remove_style_all(obj);
    lv_obj_set_style_bg_opa(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_flex_flow(obj, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(obj, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
}

lv_obj_t *ui_layout_main_create(lv_obj_t *comp_parent) {
    lv_obj_t *cui_layout;
    cui_layout = lv_obj_create(comp_parent);
    apply_container_style(cui_layout);
    lv_obj_set_width(cui_layout, 480);
    lv_obj_set_height(cui_layout, 480);
    lv_obj_set_align(cui_layout, LV_ALIGN_TOP_LEFT);
    lv_obj_set_pos(cui_layout, 0, 0);

    lv_obj_t *cui_top = lv_obj_create(cui_layout);
    apply_container_style(cui_top);
    lv_obj_set_size(cui_top, 100, 26);
    lv_obj_set_pos(cui_top, 190, 58);
    lv_obj_set_align(cui_top, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_mid_top_right = lv_obj_create(cui_layout);
    apply_container_style(cui_mid_top_right);
    lv_obj_set_size(cui_mid_top_right, 60, 40);
    lv_obj_set_pos(cui_mid_top_right, 240, 137);
    lv_obj_set_align(cui_mid_top_right, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_mid_top_left = lv_obj_create(cui_layout);
    apply_container_style(cui_mid_top_left);
    lv_obj_set_size(cui_mid_top_left, 60, 40);
    lv_obj_set_pos(cui_mid_top_left, 180, 137);
    lv_obj_set_align(cui_mid_top_left, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_mid_right = lv_obj_create(cui_layout);
    apply_container_style(cui_mid_right);
    lv_obj_set_size(cui_mid_right, 60, 26);
    lv_obj_set_pos(cui_mid_right, 240, 177);
    lv_obj_set_align(cui_mid_right, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_mid_left = lv_obj_create(cui_layout);
    apply_container_style(cui_mid_left);
    lv_obj_set_size(cui_mid_left, 60, 26);
    lv_obj_set_pos(cui_mid_left, 180, 177);
    lv_obj_set_align(cui_mid_left, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_main_left = lv_obj_create(cui_layout);
    apply_container_style(cui_main_left);
    lv_obj_set_size(cui_main_left, 50, 50);
    lv_obj_set_pos(cui_main_left, 50, 215);
    lv_obj_set_align(cui_main_left, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_main_right = lv_obj_create(cui_layout);
    apply_container_style(cui_main_right);
    lv_obj_set_size(cui_main_right, 50, 50);
    lv_obj_set_pos(cui_main_right, 380, 215);
    lv_obj_set_align(cui_main_right, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_main = lv_obj_create(cui_layout);
    apply_container_style(cui_main);
    lv_obj_set_size(cui_main, 280, 50);
    lv_obj_set_pos(cui_main, 100, 215);
    lv_obj_set_align(cui_main, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_main_sub = lv_obj_create(cui_layout);
    apply_container_style(cui_main_sub);
    lv_obj_set_size(cui_main_sub, 280, 26);
    lv_obj_set_pos(cui_main_sub, 100, 280);
    lv_obj_set_align(cui_main_sub, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_base_top = lv_obj_create(cui_layout);
    apply_container_style(cui_base_top);
    lv_obj_set_size(cui_base_top, 100, 26);
    lv_obj_set_pos(cui_base_top, 190, 370);
    lv_obj_set_align(cui_base_top, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_base_bottom = lv_obj_create(cui_layout);
    apply_container_style(cui_base_bottom);
    lv_obj_set_size(cui_base_bottom, 100, 26);
    lv_obj_set_pos(cui_base_bottom, 190, 396);
    lv_obj_set_align(cui_base_bottom, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_ring_bottom_main = lv_obj_create(cui_layout);
    apply_container_style(cui_ring_bottom_main);
    lv_obj_set_size(cui_ring_bottom_main, 100, 26);
    lv_obj_set_pos(cui_ring_bottom_main, 190, 430);
    lv_obj_set_align(cui_ring_bottom_main, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_ring_bottom_left = lv_obj_create(cui_layout);
    apply_container_style(cui_ring_bottom_left);
    lv_obj_set_size(cui_ring_bottom_left, 45, 26);
    lv_obj_set_pos(cui_ring_bottom_left, 190, 430);
    lv_obj_set_align(cui_ring_bottom_left, LV_ALIGN_TOP_LEFT);

    lv_obj_t *cui_ring_bottom_right = lv_obj_create(cui_layout);
    apply_container_style(cui_ring_bottom_right);
    lv_obj_set_size(cui_ring_bottom_right, 45, 26);
    lv_obj_set_pos(cui_ring_bottom_right, 245, 430);
    lv_obj_set_align(cui_ring_bottom_right, LV_ALIGN_TOP_LEFT);

    lv_obj_t **children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LAYOUT_MAIN_NUM);
    children[UI_COMP_LAYOUT_MAIN_ROOT] = cui_layout;
    children[UI_COMP_LAYOUT_MAIN_TOP] = cui_top;
    children[UI_COMP_LAYOUT_MAIN_MID_TOP_RIGHT] = cui_mid_top_right;
    children[UI_COMP_LAYOUT_MAIN_MID_TOP_LEFT] = cui_mid_top_left;
    children[UI_COMP_LAYOUT_MAIN_MID_RIGHT] = cui_mid_right;
    children[UI_COMP_LAYOUT_MAIN_MID_LEFT] = cui_mid_left;
    children[UI_COMP_LAYOUT_MAIN_MAIN_LEFT] = cui_main_left;
    children[UI_COMP_LAYOUT_MAIN_MAIN_RIGHT] = cui_main_right;
    children[UI_COMP_LAYOUT_MAIN_MAIN] = cui_main;
    children[UI_COMP_LAYOUT_MAIN_MAIN_SUB] = cui_main_sub;
    children[UI_COMP_LAYOUT_MAIN_BASE_TOP] = cui_base_top;
    children[UI_COMP_LAYOUT_MAIN_BASE_BOTTOM] = cui_base_bottom;
    children[UI_COMP_LAYOUT_MAIN_RING_BOTTOM_MAIN] = cui_ring_bottom_main;
    children[UI_COMP_LAYOUT_MAIN_RING_BOTTOM_LEFT] = cui_ring_bottom_left;
    children[UI_COMP_LAYOUT_MAIN_RING_BOTTOM_RIGHT] = cui_ring_bottom_right;
    lv_obj_add_event_cb(cui_layout, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_layout, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_layout_main_create_hook(cui_layout);
    return cui_layout;
}
