// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef _GAGGIMATE_UI_COMP_HOOK_H
#define _GAGGIMATE_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_dials_create_hook(lv_obj_t *comp);
void ui_comp_layout_main_create_hook(lv_obj_t *comp);
void ui_comp_layout_settings_create_hook(lv_obj_t *comp);
void ui_comp_layout_settings_single_create_hook(lv_obj_t *comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
