// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../ui.h"

// COMPONENT dials

#if defined(LV_USE_DRAW_MASK) && LV_USE_DRAW_MASK
typedef struct {
    lv_draw_mask_angle_param_t mask;
    int16_t mask_id;
} dial_gap_mask_t;
#else
typedef struct {
    int16_t dummy;
} dial_gap_mask_t;
#endif

#if defined(LV_USE_DRAW_MASK) && LV_USE_DRAW_MASK
static void dial_indicator_draw_event(lv_event_t *e) {
    lv_event_code_t code = lv_event_get_code(e);
    dial_gap_mask_t *mask = (dial_gap_mask_t *)lv_event_get_user_data(e);
    if (!mask) {
        return;
    }

    if (code == LV_EVENT_DRAW_MAIN_BEGIN) {
        lv_draw_mask_angle_init(&mask->mask, 240, 240, 284, 256);
        mask->mask_id = lv_draw_mask_add(&mask->mask, NULL);
    } else if (code == LV_EVENT_DRAW_MAIN_END) {
        lv_draw_mask_remove_id(mask->mask_id);
        lv_draw_mask_free_param(&mask->mask);
    }
}

static void dial_indicator_delete_event(lv_event_t *e) {
    dial_gap_mask_t *mask = (dial_gap_mask_t *)lv_event_get_user_data(e);
    if (mask) {
        lv_mem_free(mask);
    }
}
#endif

static void dial_line_delete_event(lv_event_t *e) {
    lv_point_t *points = (lv_point_t *)lv_event_get_user_data(e);
    if (points) {
        lv_mem_free(points);
    }
}

lv_obj_t *ui_dials_create(lv_obj_t *comp_parent) {

    lv_obj_t *cui_dials;
    cui_dials = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_dials);
    lv_obj_set_width(cui_dials, 480);
    lv_obj_set_height(cui_dials, 480);
    lv_obj_set_align(cui_dials, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_dials, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

#if defined(LV_USE_DRAW_MASK) && LV_USE_DRAW_MASK
    dial_gap_mask_t *temp_mask = lv_mem_alloc(sizeof(dial_gap_mask_t));
    dial_gap_mask_t *pressure_mask = lv_mem_alloc(sizeof(dial_gap_mask_t));
#else
    dial_gap_mask_t *temp_mask = NULL;
    dial_gap_mask_t *pressure_mask = NULL;
#endif

    lv_obj_t *cui_tempGauge;
    cui_tempGauge = lv_img_create(cui_dials);
    lv_img_set_src(cui_tempGauge, &ui_img_minimal_indicator_temp);
    lv_obj_set_pos(cui_tempGauge, 15, 95);
    lv_obj_set_align(cui_tempGauge, LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(cui_tempGauge, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(cui_tempGauge, LV_OBJ_FLAG_SCROLLABLE);
    lv_img_set_pivot(cui_tempGauge, 225, 145);
#if defined(LV_USE_DRAW_MASK) && LV_USE_DRAW_MASK
    if (temp_mask) {
        lv_obj_add_event_cb(cui_tempGauge, dial_indicator_draw_event, LV_EVENT_DRAW_MAIN_BEGIN, temp_mask);
        lv_obj_add_event_cb(cui_tempGauge, dial_indicator_draw_event, LV_EVENT_DRAW_MAIN_END, temp_mask);
        lv_obj_add_event_cb(cui_tempGauge, dial_indicator_delete_event, LV_EVENT_DELETE, temp_mask);
    }
#endif

    lv_obj_t *cui_tempTarget;
    cui_tempTarget = lv_line_create(cui_dials);
    lv_obj_set_size(cui_tempTarget, 480, 480);
    lv_obj_set_pos(cui_tempTarget, 0, 0);
    lv_obj_add_flag(cui_tempTarget, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(cui_tempTarget, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_line_width(cui_tempTarget, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(cui_tempTarget, lv_color_hex(0xED2024), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(cui_tempTarget, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_point_t *temp_points = lv_mem_alloc(sizeof(lv_point_t) * 2);
    if (temp_points) {
        temp_points[0].x = 240;
        temp_points[0].y = 240;
        temp_points[1].x = 240;
        temp_points[1].y = 240;
        lv_line_set_points(cui_tempTarget, temp_points, 2);
        lv_obj_set_user_data(cui_tempTarget, temp_points);
        lv_obj_add_event_cb(cui_tempTarget, dial_line_delete_event, LV_EVENT_DELETE, temp_points);
    }

    lv_obj_t *cui_pressureGauge;
    cui_pressureGauge = lv_img_create(cui_dials);
    lv_img_set_src(cui_pressureGauge, &ui_img_minimal_indicator_pressure);
    lv_obj_set_pos(cui_pressureGauge, 15, 95);
    lv_obj_set_align(cui_pressureGauge, LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(cui_pressureGauge, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(cui_pressureGauge, LV_OBJ_FLAG_SCROLLABLE);
    lv_img_set_pivot(cui_pressureGauge, 225, 145);
#if defined(LV_USE_DRAW_MASK) && LV_USE_DRAW_MASK
    if (pressure_mask) {
        lv_obj_add_event_cb(cui_pressureGauge, dial_indicator_draw_event, LV_EVENT_DRAW_MAIN_BEGIN, pressure_mask);
        lv_obj_add_event_cb(cui_pressureGauge, dial_indicator_draw_event, LV_EVENT_DRAW_MAIN_END, pressure_mask);
        lv_obj_add_event_cb(cui_pressureGauge, dial_indicator_delete_event, LV_EVENT_DELETE, pressure_mask);
    }
#endif

    lv_obj_t *cui_pressureTarget;
    cui_pressureTarget = lv_line_create(cui_dials);
    lv_obj_set_size(cui_pressureTarget, 480, 480);
    lv_obj_set_pos(cui_pressureTarget, 0, 0);
    lv_obj_add_flag(cui_pressureTarget, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(cui_pressureTarget, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_line_width(cui_pressureTarget, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(cui_pressureTarget, lv_color_hex(0x007BC1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(cui_pressureTarget, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_point_t *pressure_points = lv_mem_alloc(sizeof(lv_point_t) * 2);
    if (pressure_points) {
        pressure_points[0].x = 240;
        pressure_points[0].y = 240;
        pressure_points[1].x = 240;
        pressure_points[1].y = 240;
        lv_line_set_points(cui_pressureTarget, pressure_points, 2);
        lv_obj_set_user_data(cui_pressureTarget, pressure_points);
        lv_obj_add_event_cb(cui_pressureTarget, dial_line_delete_event, LV_EVENT_DELETE, pressure_points);
    }

    lv_obj_t *cui_pressureText;
    cui_pressureText = lv_label_create(cui_dials);
    lv_obj_set_width(cui_pressureText, 60);
    lv_obj_set_height(cui_pressureText, LV_SIZE_CONTENT);
    lv_obj_set_x(cui_pressureText, 50);
    lv_obj_set_y(cui_pressureText, -205);
    lv_obj_set_align(cui_pressureText, LV_ALIGN_CENTER);
    lv_label_set_text(cui_pressureText, "9 bar");
    lv_obj_set_style_text_align(cui_pressureText, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_pressureText, &ui_font_sfprodisplaybold_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(cui_pressureText, lv_color_hex(0x007BC1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_pressureText, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *cui_tempText;
    cui_tempText = lv_label_create(cui_dials);
    lv_obj_set_width(cui_tempText, 60);
    lv_obj_set_height(cui_tempText, LV_SIZE_CONTENT);
    lv_obj_set_x(cui_tempText, -50);
    lv_obj_set_y(cui_tempText, -205);
    lv_obj_set_align(cui_tempText, LV_ALIGN_CENTER);
    lv_label_set_text(cui_tempText, "92°C");
    lv_obj_set_style_text_align(cui_tempText, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_tempText, &ui_font_sfprodisplaybold_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(cui_tempText, lv_color_hex(0xEF3A24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_tempText, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *cui_tempIcon;
    cui_tempIcon = lv_img_create(cui_dials);
    lv_img_set_src(cui_tempIcon, &ui_img_1951499226);
    lv_obj_set_width(cui_tempIcon, LV_SIZE_CONTENT);  /// 40
    lv_obj_set_height(cui_tempIcon, LV_SIZE_CONTENT); /// 40
    lv_obj_set_x(cui_tempIcon, -85);
    lv_obj_set_y(cui_tempIcon, 200);
    lv_obj_set_align(cui_tempIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_tempIcon, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(cui_tempIcon, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(cui_tempIcon, 150);
    lv_obj_set_style_img_recolor(cui_tempIcon, lv_color_hex(0xF62C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(cui_tempIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *cui_Image6;
    cui_Image6 = lv_img_create(cui_dials);
    lv_img_set_src(cui_Image6, &ui_img_1220767159);
    lv_obj_set_width(cui_Image6, LV_SIZE_CONTENT);  /// 40
    lv_obj_set_height(cui_Image6, LV_SIZE_CONTENT); /// 40
    lv_obj_set_x(cui_Image6, 85);
    lv_obj_set_y(cui_Image6, 200);
    lv_obj_set_align(cui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image6, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(cui_Image6, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(cui_Image6, 150);
    lv_obj_set_style_img_recolor(cui_Image6, lv_color_hex(0x2CA4F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(cui_Image6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t **children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_DIALS_NUM);
    children[UI_COMP_DIALS_DIALS] = cui_dials;
    children[UI_COMP_DIALS_TEMPGAUGE] = cui_tempGauge;
    children[UI_COMP_DIALS_TEMPTARGET] = cui_tempTarget;
    children[UI_COMP_DIALS_PRESSUREGAUGE] = cui_pressureGauge;
    children[UI_COMP_DIALS_PRESSURETARGET] = cui_pressureTarget;
    children[UI_COMP_DIALS_PRESSURETEXT] = cui_pressureText;
    children[UI_COMP_DIALS_TEMPTEXT] = cui_tempText;
    children[UI_COMP_DIALS_TEMPICON] = cui_tempIcon;
    children[UI_COMP_DIALS_IMAGE6] = cui_Image6;
    lv_obj_add_event_cb(cui_dials, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_dials, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_dials_create_hook(cui_dials);
    return cui_dials;
}
