// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef _UI_COMP_LAYOUT_SETTINGS_SINGLE_H
#define _UI_COMP_LAYOUT_SETTINGS_SINGLE_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT layout_settings_single
#define UI_COMP_LAYOUT_SETTINGS_SINGLE_ROOT 0
#define UI_COMP_LAYOUT_SETTINGS_SINGLE_TITLE 1
#define UI_COMP_LAYOUT_SETTINGS_SINGLE_LEFT 2
#define UI_COMP_LAYOUT_SETTINGS_SINGLE_RIGHT 3
#define UI_COMP_LAYOUT_SETTINGS_SINGLE_MAIN 4
#define UI_COMP_LAYOUT_SETTINGS_SINGLE_BASE_TOP 5
#define _UI_COMP_LAYOUT_SETTINGS_SINGLE_NUM 6
lv_obj_t *ui_layout_settings_single_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
